version: 2
sources:
  - name: central_raw_sari_ili
    database: SHIELD
    schema: central_raw_sari_ili
    tables:
      - name: sari_ili_data
        description: This table contains raw data for SARI-ILI
  - name: central_raw_khis
    database: SHIELD
    schema: central_raw_khis
    tables:
      - name: moh_505
        description: This table contains raw data for MOH 505 form
      - name: moh_705
        description: This table contains raw data for MOH 705 form
  - name: central_raw_mdharura
    database: SHIELD
    schema: central_raw_mdharura
    tables:
      - name: mdharura_ebs_linelist
        description: This table contains raw data for M-dharura app
      - name: mdharura_ebs_aggregate
        description: This table contains raw aggregate data for M-dharura app
  - name: staging
    database: SHIELD
    schema: staging
    tables:
      - name: stg_ebridge_output_diarrhoeal_disease
        description: This table contains raw data from the e-bridge diarrhoeal ML model
      - name: stg_ebridge_output_respiratory_illness
        description: This table contains raw data from the e-bridge respiratory ML model

  - name: central_raw_mortality
    database: SHIELD
    schema: central_raw_mortality
    tables:
      - name: mortality_surveillance
        description: This table contains raw data for the mortality surveillance
  - name: central_raw_afi
    database: SHIELD
    schema: central_raw_afi
    tables:
      - name: screening
        description: This table contains raw data for AFI screening
      - name: lab_results
      - name: afi_surveillance_table
      - name: malaria_rdt
      - name: enroll_and_household_info
      - name: history_and_physical_exam
      - name: afi_tac_results
      - name: physical_abstraction
      - name: sample_collection
      - name: leptospirosis_rdt
      - name: npop_swab
      - name: sarscov_merged_results
      - name: nasal_swab
      - name: throat_swab
      - name: clinical_course_outcome
  - name: central_raw_krcs
    database: SHIELD
    schema: central_raw_krcs
    tables:
      - name: cbs
        description: This table contains raw data for Red Cross CBS
  - name: central_raw_ears
    database: SHIELD
    schema: central_raw_ears
    tables:
      - name: veoc_covid_linelist_results
  - name: central_raw_palladium
    database: SHIELD
    schema: central_raw_palladium
    tables:
      - name: subject
        description: This table contains raw data for passive surveillance subject
      - name: complaint
        description: This table contains raw data for passive surveillance complaint
      - name: illness_case
        description: This table contains raw data for passive surveillance illness case
      - name: diagnosis
        description: This table contains raw data for passive surveillance diagnosis
      - name: flagged_condition
        description: This table contains raw data for passive surveillance flagged condition
      - name: lab
        description: This table contains raw data for passive surveillance lab
      - name: vital_sign
        description: This table contains raw data for passive surveillance vital sign
      - name: risk_factor
        description: This table contains raw data for passive surveillance risk factor
      - name: vaccination
        description: This table contains raw data for passive surveillance vaccination